In [1]:
import tensorflow as tf

In [2]:
# sequebce is 4, batch 3
x = [[5, 6, 7],
     [7, 6, 0],
     [0, 7, 0],
      [0,8,0]]
xl = [2, 4, 1]

In [3]:
encoder_inputs = tf.constant(x, dtype=tf.int32, name='encoder_inputs')
encoder_inputs_length = tf.constant(xl, dtype=tf.int32, name='encoder_inputs_length')
decoder_targets = tf.constant(x, dtype=tf.int32, name='decoder_targets')
decoder_targets_length = tf.constant(xl, dtype=tf.int32, name='decoder_targets_length')

In [5]:
PAD = 0
EOS = 1
batch_size = 3

In [7]:
EOS_SLICE = tf.ones([1, batch_size], dtype=tf.int32) * EOS
PAD_SLICE = tf.ones([1, batch_size], dtype=tf.int32) * PAD

In [8]:
decoder_train_inputs = tf.concat([EOS_SLICE, decoder_targets], axis=0)

In [9]:
decoder_train_length = decoder_targets_length + 1

In [16]:
decoder_train_targets = tf.concat([decoder_targets, PAD_SLICE], axis=0)
decoder_train_targets_seq_len, _ = tf.unstack(tf.shape(decoder_train_targets)) 
decoder_train_targets_eos_mask = tf.one_hot(decoder_train_length - 1,
                                                        decoder_train_targets_seq_len,
                                                        on_value=EOS, off_value=PAD,
                                                        dtype=tf.int32)
decoder_train_targets_eos_mask = tf.transpose(decoder_train_targets_eos_mask, [1, 0])

            # hacky way using one_hot to put EOS symbol at the end of target sequence
decoder_train_targets = tf.add(decoder_train_targets,
                                           decoder_train_targets_eos_mask)

In [23]:
with tf.Session() as sess:
    seq_len, eos_mask, targets = sess.run([decoder_train_targets_seq_len, decoder_train_targets_eos_mask,decoder_train_targets])
    print(seq_len)
    print(eos_mask)
    print(targets)

5
[[0 0 0]
 [0 0 1]
 [1 0 0]
 [0 0 0]
 [0 1 0]]
[[5 6 7]
 [7 6 1]
 [1 7 0]
 [0 8 0]
 [0 1 0]]


In [13]:
print(train_inputs)

[[1 1 1]
 [5 6 7]
 [7 6 0]
 [0 7 0]
 [0 8 0]]
